Пример использования:

	$validator = new Validator();
	$validator->check($source, ['username' => ['required' => true, 'min' => 2, 'unique' => ['Mark', 'Todd', 'User']]]);

описание:
	
	Компонент Validator это инстумент для валидации переданных данных.
	Компонент Validator содержит 3 открытых функции для использования: check(...), errors и passed.
	Для использования этих функций надо подключить класс Router, создать объект класса Router и использовать функции на нём.

	Функция check(...) реализует валидацию. Она принимает 2 параметра (array $source, array $items).
	-Первый: $source это указатель, в каком массиве будут переданы данные для валидации. Например $_POST;
	-Второй: $items это перечисление правил по которым надо проверять данные массива. Записываются в виде $название идентификатора поля данных => [массив с правилами].
		[массив с правилами] - это перечисление названий правил ($key) и их условий ($value). Реализованны следующие правила:
			'min' - кол-во символов должно быть больше указанного значения. Принимает значение типа int;
			'max' - кол-во символов должно быть меньше указанного значения. Принимает значение типа int;
			'matches' - значение поля должно совпадать со значением указанного поля. Принимает значение типа string;
			'unique' - смотрит, чтобы проверяемое значение не нашлось в переданном массиве значений. Принимает значение типа array;
			'email' - проверяет подходит ли проверяемое поле под параметры типа e-mail. Принимает значение типа string;
			'float' - проверяет подходит ли проверяемое поле под параметры типа float;
			'integer' - проверяет подходит ли проверяемое поле под параметры типа integer.
	Правила можно дополнять, указав их в методе check в конструкции switch-case как новый case.
	Если проверяемое поле не прошло проверку, то в массив errors записывается ошибка с описанием причины, а так-же в значение passed записывается значение false.
	Если провека пройдена и массив errors является пустым, то проверка считается пройденной и в значеню passed присваевается true.
	
	Фукция errors() возвращает массив с ошибками, которые были записаны в результате метода check(...).

	Фукция passed() возвращает true, если в результате метода check(...) массив errors оказался пустым или false в обратном случае.

	